/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.Ventanas;

import com.itson.Utilidades.EncriptadorSecreto;
import static com.itson.Ventanas.Proyecto02BasesDeDatosAvanzadas.entityManager;
import com.itson.daos.LicenciaDAO;
import com.itson.daos.PlacaDAO;
import com.itson.daos.VehiculoDAO;
import com.itson.dominio.Persona;
import com.itson.dominio.Placa;
import com.itson.dominio.Vehiculo;
import java.time.LocalDate;
import javax.persistence.EntityNotFoundException;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Erick
 */
public class PantallaPlacas extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPlacas
     */
    private Vehiculo vehiculo;
    private Persona selectedPersona;
    private EncriptadorSecreto encriptador = new EncriptadorSecreto();
    

    
    public PantallaPlacas() {
        initComponents();
        updateData();
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEscogePersona = new javax.swing.JButton();
        textFieldCosto = new javax.swing.JTextField();
        textFieldPlacas = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        textFieldPersona = new javax.swing.JTextField();
        textFieldSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setText("EXPEDICIÓN DE PLACAS");

        btnEscogePersona.setText("Escoge persona");
        btnEscogePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogePersonaActionPerformed(evt);
            }
        });

        textFieldCosto.setEditable(false);
        textFieldCosto.setText("$1,500");
        textFieldCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCostoActionPerformed(evt);
            }
        });

        textFieldPlacas.setEditable(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        textFieldPersona.setEditable(false);
        textFieldPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPersonaActionPerformed(evt);
            }
        });

        textFieldSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSerieActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de serie:");

        jLabel3.setText("Persona:");

        jLabel4.setText("Costo:");

        jLabel5.setText("Placas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(btnEscogePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldCosto)
                                .addComponent(textFieldPlacas)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldPersona)
                                .addComponent(textFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(textFieldPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEscogePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscogePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogePersonaActionPerformed

        PantallaSeleccionaUsuario pantallaSeleccionPersona = new PantallaSeleccionaUsuario(this);
        pantallaSeleccionPersona.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEscogePersonaActionPerformed

    public void getPersona(PantallaSeleccionaUsuario pantallaSeleccionPersona){
        selectedPersona=pantallaSeleccionPersona.sendPersona();
        textFieldPersona.setText(encriptador.desencriptar(selectedPersona.getNombre()));
      
    }

    public void getVehiculo(RegistroVehiculo registroVehiculo) {
        vehiculo = registroVehiculo.sendVehiculo();
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        LicenciaDAO licenciaDAO = new LicenciaDAO();
        
        if (licenciaDAO.checkDriversLicense(entityManager, selectedPersona)){
            
            VehiculoDAO vehiculoDAO = new VehiculoDAO();
            try {
                vehiculo = vehiculoDAO.getListaVehiculo(entityManager, null, null, null, null, textFieldSerie.getText(), null).get(0);
            } catch (EntityNotFoundException e) {
                RegistroVehiculo registroVehiculo = new RegistroVehiculo(this, textFieldSerie.getText());
                this.setVisible(false);
                registroVehiculo.setVisible(true);
            }
            if (vehiculo != null) {
                PlacaDAO placaDAO = new PlacaDAO();
                placaDAO.insert(entityManager, placaDAO.create(entityManager, LocalDate.now(), null, vehiculo, licenciaDAO, selectedPersona), vehiculoDAO);
                PantallaInicio pantallaInicio = new PantallaInicio();
                pantallaInicio.setVisible(true);
                this.dispose();
            }
        } else {
            showMessageDialog(null, "La persona no tiene licencia vigente");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void textFieldPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPersonaActionPerformed

    private void textFieldSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSerieActionPerformed

        

    }//GEN-LAST:event_textFieldSerieActionPerformed

    private void textFieldCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCostoActionPerformed

    protected void updateData(){
        PlacaDAO placasDAO = new PlacaDAO();
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Placas:");
        stringBuilder.append(placasDAO.generateMatricula(entityManager));
        textFieldPlacas.setText(stringBuilder.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPlacas().setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEscogePersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textFieldCosto;
    private javax.swing.JTextField textFieldPersona;
    private javax.swing.JTextField textFieldPlacas;
    private javax.swing.JTextField textFieldSerie;
    // End of variables declaration//GEN-END:variables
}
