/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.Ventanas;

import com.itson.Utilidades.EncriptadorSecreto;
import static com.itson.Ventanas.Proyecto02BasesDeDatosAvanzadas.entityManager;
import static com.itson.Ventanas.Proyecto02BasesDeDatosAvanzadas.mainScreen;
import com.itson.daos.LicenciaDAO;
import com.itson.daos.PlacaDAO;
import com.itson.daos.PrecioPlacaDAO;
import com.itson.daos.VehiculoDAO;
import com.itson.dominio.Persona;
import com.itson.dominio.PrecioPlaca;
import com.itson.dominio.Vehiculo;
import com.itson.dominio.Vigencia;
import java.time.LocalDate;
import javax.persistence.EntityNotFoundException;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Erick
 */
public class PantallaPlacas extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPlacas
     */
    private Vehiculo vehiculo;
    private Persona selectedPersona;
    private EncriptadorSecreto encriptador = new EncriptadorSecreto();
    private PrecioPlacaDAO precioPlacaDAO = new PrecioPlacaDAO();
    private VehiculoDAO vehiculoDAO = new VehiculoDAO();
    private boolean vehiculoValido = false;

    public PantallaPlacas() {
        initComponents();
        updateData();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEscogePersona = new javax.swing.JButton();
        textFieldCosto = new javax.swing.JTextField();
        textFieldMatricula = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        textFieldPersona = new javax.swing.JTextField();
        textFieldSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCalcularCosto = new javax.swing.JButton();
        btnVerificaVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setText("EXPEDICIÓN DE PLACAS");

        btnEscogePersona.setText("Escoge persona");
        btnEscogePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogePersonaActionPerformed(evt);
            }
        });

        textFieldCosto.setEditable(false);
        textFieldCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCostoActionPerformed(evt);
            }
        });

        textFieldMatricula.setEditable(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        textFieldPersona.setEditable(false);
        textFieldPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPersonaActionPerformed(evt);
            }
        });

        textFieldSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSerieActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de serie:");

        jLabel3.setText("Persona:");

        jLabel4.setText("Costo:");

        jLabel5.setText("Matricula:");

        btnCalcularCosto.setText("Calcular costo");
        btnCalcularCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCostoActionPerformed(evt);
            }
        });

        btnVerificaVehiculo.setText("Verifica vehiculo");
        btnVerificaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(btnEscogePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldCosto)
                                .addComponent(textFieldMatricula)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCalcularCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnVerificaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldPersona)
                                .addComponent(textFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(textFieldPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEscogePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscogePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogePersonaActionPerformed

        PantallaSeleccionaPersona pantallaSeleccionPersona = new PantallaSeleccionaPersona(this);
        pantallaSeleccionPersona.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEscogePersonaActionPerformed

    public void getPersona(PantallaSeleccionaPersona pantallaSeleccionPersona) {
        selectedPersona = pantallaSeleccionPersona.sendPersona();
        textFieldPersona.setText(encriptador.desencriptar(selectedPersona.getNombre()));

    }

    public void updateCosto() {

        PrecioPlaca preciosPlaca = precioPlacaDAO.getPrecioPlaca(entityManager);

        Double costo = 0.0;
        if (vehiculo.getPlacas().isEmpty()) {
            costo = preciosPlaca.getPrecioVehiculoNuevo();
        } else {
            costo = preciosPlaca.getPrecioVehiculoViejo();
        }
        textFieldCosto.setText("$" + costo);
    }

    public void getVehiculo(RegistroVehiculo registroVehiculo) {
        vehiculo = registroVehiculo.sendVehiculo();
    }

    private void verificarNumeroSerie() {
        try {
            vehiculo = vehiculoDAO.getListaVehiculo(entityManager, null, null, null, null, textFieldSerie.getText(), null).get(0);
        } catch (EntityNotFoundException e) {
            RegistroVehiculo registroVehiculo = new RegistroVehiculo(this, textFieldSerie.getText());
            this.setVisible(false);
            registroVehiculo.setVisible(true);
        } finally {
            vehiculoValido = true;
        }
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        LicenciaDAO licenciaDAO = new LicenciaDAO();

        if (selectedPersona != null) {
            if (!selectedPersona.getTramite().isEmpty()) {
                if (!textFieldSerie.getText().isBlank()) {
                    if (licenciaDAO.checkDriversLicense(entityManager, selectedPersona)) {
                        if (vehiculoValido) {
                            if (vehiculo != null) {
                                if (!textFieldCosto.getText().isBlank()) {
                                    PlacaDAO placaDAO = new PlacaDAO();
                                    placaDAO.insert(entityManager, placaDAO.create(entityManager, LocalDate.now(), null, vehiculo, licenciaDAO, selectedPersona, textFieldMatricula.getText().substring(7)), vehiculoDAO);
                                    showMessageDialog(null, "Placa registrada");
                                    mainScreen.setVisible(true);
                                    this.dispose();
                                } else {
                                    showMessageDialog(null, "Calcule el precio para asegurarse de que quiere seguir con el tramite ^^");
                                }
                            }
                        }
                        else{
                             showMessageDialog(null, "Ingrese un vehiculo válido (Número de serie)");   
                                }
                    } else {
                        showMessageDialog(null, "La persona no tiene licencia activa");
                    }
                } else {
                    showMessageDialog(null, "Ingrese un número de serie");
                }
            } else {
                System.out.println(selectedPersona.getTramite());
                showMessageDialog(null, "La persona no tiene licencia");
            }

        } else {
            showMessageDialog(null, "Escoja una persona");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void textFieldPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPersonaActionPerformed

    private void textFieldSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSerieActionPerformed

    }//GEN-LAST:event_textFieldSerieActionPerformed

    private void textFieldCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCostoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        mainScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCalcularCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCostoActionPerformed
        if (vehiculo != null) {
            updateCosto();
        } else {
            showMessageDialog(null, "Ingrese un vehiculo válido (Número de serie)");
        }
    }//GEN-LAST:event_btnCalcularCostoActionPerformed

    private void btnVerificaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaVehiculoActionPerformed

        if (!textFieldSerie.getText().isBlank()) {
            verificarNumeroSerie();
        } else {
            showMessageDialog(null, "Ingrese un número de serie");
        }

    }//GEN-LAST:event_btnVerificaVehiculoActionPerformed

    protected void updateData() {
        PlacaDAO placasDAO = new PlacaDAO();
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Placas:");
        stringBuilder.append(placasDAO.generateMatricula(entityManager));
        textFieldMatricula.setText(stringBuilder.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPlacas().setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCalcularCosto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEscogePersona;
    private javax.swing.JButton btnVerificaVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textFieldCosto;
    private javax.swing.JTextField textFieldMatricula;
    private javax.swing.JTextField textFieldPersona;
    private javax.swing.JTextField textFieldSerie;
    // End of variables declaration//GEN-END:variables
}
